# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build and Test

on:
    push:
        branches: ['main']
    pull_request:
        branches: ['main']

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Install node and npm
              uses: actions/setup-node@v4
              with:
                  node-version: '22.x'
                  cache: 'npm'

            - name: Install Xvfb
              run: sudo apt-get install -y xvfb

            - name: Start Xvfb
              run: Xvfb :99 & export DISPLAY=:99

            - name: Install npm packages
              run: npm ci

            - name: Run tests
              run: npm run test
              env:
                  DISPLAY: :99
